gen3_7dof:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.02  # Increased to 20ms
  solve_type: Distance # smooth trajectory following