# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - gen3_lite_controller
    - gen3_lite_2f_controller

  gen3_lite_controller:
    type: FollowJointTrajectory
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    action_ns: follow_joint_trajectory
    default: true
<<<<<<< HEAD
  gen3_lite_2f_controller:
    type: GripperCommand
    joints:
      - right_finger_bottom_joint
    action_ns: gripper_cmd
    default: true
=======

  gen3_lite_2f_controller:
    type: FollowJointTrajectory
    joints:
      - right_finger_bottom_joint
      - right_finger_tip_joint
      - left_finger_bottom_joint
      - left_finger_tip_joint
    action_ns: follow_joint_trajectory
    default: true
>>>>>>> master
