name: rlds_env
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.3.2=h166bdaf_0
  - av=9.1.0=py39h8d29763_0
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.33.1=heb4867d_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.16.0=h6cf1ce9_1008
  - dbus=1.13.6=h48d8840_2
  - expat=2.6.2=h59595ed_0
  - ffmpeg=4.3.2=h37c90e5_3
  - fontconfig=2.14.2=h14ed4e7_0
  - freeglut=3.2.2=h9c3ff4c_1
  - freetype=2.12.1=h267a509_2
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - glib=2.68.4=h9c3ff4c_0
  - glib-tools=2.68.4=h9c3ff4c_0
  - gmp=6.3.0=hac33072_2
  - gnutls=3.6.13=h85f3911_1
  - graphite2=1.3.13=h59595ed_1003
  - gst-plugins-base=1.18.5=hf529b03_0
  - gstreamer=1.18.5=h76c114f_0
  - harfbuzz=3.0.0=h83ec7ef_1
  - hdf5=1.12.1=nompi_h2386368_104
  - icu=68.2=h9c3ff4c_0
  - jasper=2.0.33=h0ff4b12_1
  - jpeg=9e=h0b41bf4_3
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.19.3=h3790be6_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.14=h6ed2654_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libblas=3.9.0=24_linux64_openblas
  - libcblas=3.9.0=24_linux64_openblas
  - libcurl=7.86.0=h7bff187_1
  - libdeflate=1.14=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libevent=2.1.10=h9b69904_4
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.3=h58526e2_2
  - libgcc-ng=13.1.0=he5830b7_0
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgfortran-ng=13.2.0=h69a702a_0
  - libgfortran5=13.2.0=ha4646dd_0
  - libglib=2.68.4=h3e27bee_0
  - libglu=9.0.0=he1b5a44_1001
  - libgomp=13.1.0=he5830b7_0
  - libiconv=1.17=hd590300_2
  - liblapack=3.9.0=24_linux64_openblas
  - liblapacke=3.9.0=24_linux64_openblas
  - libllvm11=11.1.0=he0ac6c6_5
  - libnghttp2=1.51.0=hdcd2b5c_0
  - libogg=1.3.5=h4ab18f5_0
  - libopenblas=0.3.27=pthreads_hac2b453_1
  - libopencv=4.5.3=py39ha7f30a5_5
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.43=h2797004_0
  - libpq=13.8=hd77ab85_0
  - libprotobuf=3.18.3=h6239696_0
  - libsqlite=3.42.0=h2797004_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-ng=13.1.0=hfd8a6a1_0
  - libtiff=4.4.0=h82bc61c_5
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h72842e0_0
  - libzlib=1.2.13=hd590300_5
  - mysql-common=8.0.32=h14678bc_0
  - mysql-libs=8.0.32=h54cf53e_0
  - ncurses=6.4=hcb278e6_0
  - nettle=3.6=he412f7d_0
  - nspr=4.35=h27087fc_0
  - nss=3.92=h1d7d5a4_0
  - opencv=4.5.3=py39hf3d152e_5
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.0=h7d73246_1
  - openssl=1.1.1w=hd590300_0
  - pandas=2.2.2=py39hfc16268_1
  - pcre=8.45=h9c3ff4c_0
  - pip=23.2.1=pyhd8ed1ab_0
  - pixman=0.43.2=h59595ed_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - py-opencv=4.5.3=py39hef51801_5
  - python=3.9.0=hffdb5ce_5_cpython
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.9=8_cp39
  - qt=5.12.9=hda022c4_4
  - readline=8.2=h8228510_1
  - setuptools=68.0.0=pyhd8ed1ab_0
  - sqlite=3.42.0=h2c6b66d_0
  - tk=8.6.12=h27826a3_0
  - tzdata=2023c=h71feb2d_0
  - wheel=0.41.0=pyhd8ed1ab_0
  - x264=1!161.3030=h7f98852_1
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - absl-py==1.4.0
      - anyio==3.7.1
      - apache-beam==2.49.0
      - appdirs==1.4.4
      - array-record==0.4.0
      - astunparse==1.6.3
      - cachetools==5.3.1
      - certifi==2023.7.22
      - charset-normalizer==3.2.0
      - click==8.1.6
      - cloudpickle==2.2.1
      - contourpy==1.1.0
      - crcmod==1.7
      - cycler==0.11.0
      - dill==0.3.1.1
      - dm-tree==0.1.8
      - dnspython==2.4.0
      - docker-pycreds==0.4.0
      - docopt==0.6.2
      - etils==1.3.0
      - exceptiongroup==1.1.2
      - fastavro==1.8.2
      - fasteners==0.18
      - flatbuffers==23.5.26
      - fonttools==4.41.1
      - gast==0.4.0
      - gitdb==4.0.10
      - gitpython==3.1.32
      - google-auth==2.22.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - googleapis-common-protos==1.59.1
      - grpcio==1.56.2
      - h11==0.14.0
      - h5py==3.9.0
      - hdfs==2.7.0
      - httpcore==0.17.3
      - httplib2==0.22.0
      - idna==3.4
      - importlib-metadata==6.8.0
      - importlib-resources==6.0.0
      - keras==2.13.1
      - kiwisolver==1.4.4
      - libclang==16.0.6
      - markdown==3.4.3
      - markupsafe==2.1.3
      - matplotlib==3.7.2
      - numpy==1.24.3
      - oauthlib==3.2.2
      - objsize==0.6.1
      - opt-einsum==3.3.0
      - orjson==3.9.2
      - packaging==23.1
      - pathtools==0.1.2
      - pillow==10.0.0
      - plotly==5.15.0
      - promise==2.3
      - proto-plus==1.22.3
      - protobuf==4.23.4
      - psutil==5.9.5
      - pyarrow==11.0.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pydot==1.4.2
      - pymongo==4.4.1
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pytz==2023.3
      - pyyaml==6.0.1
      - regex==2023.6.3
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - sentry-sdk==1.28.1
      - setproctitle==1.3.2
      - six==1.16.0
      - smmap==5.0.0
      - sniffio==1.3.0
      - tenacity==8.2.2
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.1
      - tensorflow==2.13.0
      - tensorflow-datasets==4.9.2
      - tensorflow-estimator==2.13.0
      - tensorflow-hub==0.14.0
      - tensorflow-io-gcs-filesystem==0.32.0
      - tensorflow-metadata==1.13.1
      - termcolor==2.3.0
      - toml==0.10.2
      - tqdm==4.65.0
      - typing-extensions==4.5.0
      - urllib3==1.26.16
      - wandb==0.15.6
      - werkzeug==2.3.6
      - wrapt==1.15.0
      - zipp==3.16.2
      - zstandard==0.21.0
prefix: /home/yuandi/miniforge3/envs/rlds_env
